Speakers
sntgopl/Capstone-html-css-js pull request #1
Opened 2022-07-28 20:49 UTC by sntgopl

-I'll leave the link to the presentation video here: https://www.loom.com/share/d7fe138b051a4b55aa148799586d8194
-Created a pull request for the review of my first capstone project.
-Created index html and css file with both mobile and desktop version.
-Created about html and css file with both mobile and desktop version.
-Created Javascript index file for menu deployment for mobile version.
-Created Speakers js file for index speaker section deployment in mobile version.
-Created pull request for review.

2022-07-28 22:04 UTC, elisha2kyakpo1 requested changes
Hi 👋 @sntgopl, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- The PR title and description looks professional 👍
- No linter errors 👍
- Good and descriptive commit messages 👍


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 22:04 UTC, elisha2kyakpo1 commented on README.md
> +
- [ ] Kindly deploy the app, using GitHub pages, and make the app link available in the readme file. The project should be deployed properly, all pages, links, and images should work as expected.

2022-07-28 22:04 UTC, elisha2kyakpo1 commented on about.html
> +				</div>
- [ ] Kindly align the images properly on mobile screens, please take a look at the image below. Your pictures overlap the screen.

![image-overlap](https://user-images.githubusercontent.com/53124548/181643302-6ee0b6bb-123f-42b5-ab6b-a456cce77f03.png)

- [ ] The heading on the picture below is too big and it is overlapping as well.

![mobile-logo](https://user-images.githubusercontent.com/53124548/181643524-393e65de-c03a-493d-8e3a-24b612c6d51a.png)

2022-07-28 22:04 UTC, elisha2kyakpo1 commented on index.html
> +    	</nav>
![nav-og](https://user-images.githubusercontent.com/53124548/181643896-98228876-8a08-4cfa-b2b1-eff12c4164c9.png)
- [ ] Kindly add the top nav in black, the project has a small nav with social media icons.

2022-07-28 22:04 UTC, elisha2kyakpo1 commented on index.html
> +						<h3 id="name">Lecturer Name</h3>
- [ ] Let's reduce the space between text and an image, see the screenshots.

### Original
![speaker-og](https://user-images.githubusercontent.com/53124548/181644694-55f38cc4-0570-45f2-98e7-094181de3dc5.png)

### Yours
![speaker-yours](https://user-images.githubusercontent.com/53124548/181644538-de8f6d6f-b8e8-4d50-bc41-bd9eedf25fa6.png)

2022-07-29 17:12 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @sntgopl ✋

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" width="480" height="270" class="giphy-embed" />

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-29 17:24 UTC, merged